name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploys whenever you push to main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload website files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Path to your HTML, CSS, JS (root folder)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
